Add GitHub Actions for Husky Musher
seattleflu/husky-musher pull request #17
Opened 2022-01-28 23:08 UTC by bencap

Adds Github Actions for the Husky Musher Repo. In order for tests to run and not hit a RedCap project, also implements lazy loading of the project so that a test project instance can be used if the redcap utilities are being imported by the testing module.

2022-01-29 00:33 UTC, bencap commented
![](https://github.trello.services/images/mini-trello-icon.png) [Husky Musher - want to run doctests and unit tests in Github](https://trello.com/c/rEj66a5a/1300-husky-musher-want-to-run-doctests-and-unit-tests-in-github)

2022-01-29 00:37 UTC, bencap commented
@davereinhart I was looking into it and am not sure decorators will work in this situation. Ideally what we would want is something like this so that we can load the project if it is not loaded before running the function:
```
def lazy_load(redcap_interaction):
    def loader():
        PROJECT = LazyProject.project()
        redcap_interaction()
    return loader

@lazy_load
redcap_interaction():
    ...
```
However, this is really just doing this at the top level:
```
redcap_interaction = loader(redcap_interaction)
```

Since that happens straight away on import of the file, it doesn't give the unittest time to inject the tester 'project' into the container file and instead just loads the actual RedCap project that we don't want it to load (basically, by doing this it prevents lazy loading since the behavior of decorators actually causes it to load immediately). Let me know if I missed something, hopefully that makes sense! I thought it was perfect when I looked at it initially, but then ran into this issue while running it. Just wanted to give you a heads up as to why I did not include it.

2022-01-29 00:54 UTC, bencap commented
> 

One option though that may eliminate all those calls to make sure the project is loaded though is just to make the call at the beginning of `app.py`. That way if the `utils.redcap.py` file is ever loaded from a context where it is flask doing the loading, it will initialize the project to connect to RedCap. If the project is ever loaded from a unittest context, the unittest script will inject the dummy project.

2022-01-29 01:14 UTC, bencap commented
> That way if the `utils.redcap.py` file is ever loaded from a context where it is flask doing the loading, it will initialize the project to connect to RedCap. If the project is ever loaded from a unittest context, the unittest script will inject the dummy project.

I ended up implementing this in the latest commit, I think it is cleaner than having the duplicate code to check and initialize the redcap project.

2022-02-09 18:55 UTC, kschwabefry requested changes
Thanks for taking this on Ben. It will be great to have the GH actions set up for this repo, not to mention tests that are runnable again!!

2022-02-09 18:55 UTC, kschwabefry commented on lib/husky_musher/utils/redcap.py
> -CACHE = FanoutCache(os.environ.get("CACHE"))
I think this will require some changes to bin/dump-cache and bin/preheat-cache which currently reference CACHE directly.

2022-02-09 18:56 UTC, bencap commented on .github/workflows/ci.yaml
> +          - 3.6
Yes, I will test and update this today

2022-02-09 20:16 UTC, bencap commented
@kschwabefry Just added the changes requested, note that for the scripts in `/bin` to run, I also had to add the `husky_musher` to the path explicitly (similar to what is done in `app.py` at the root level of this directory). Just wanted to let you know why there are additional changes in those `/bin` files besides just changing the cache name.

2022-02-15 20:31 UTC, merged

2022-02-15 20:33 UTC, bencap commented
Deployed